#2.1
#*
print(type(100/5))
#**
print(type(7/2))
#***
print(type(7//2))
#****
print(type(7%2))
#*****
print(type('a'))
#******
print(type("tyza"+"."))
#*******
print(type("hola"[1+1]))
#********
print(type(len("hola")))
#*********
print(type(int("145")))
#**********
print(type(float("145")))
#***********
print(type(float(145)))
#************
print(type(str(32)))
#*************
print(type(1+2 != 3))
#**************
print(type(177%2==0))
#***************
print(type(len("nube")<=20))
